print.dyadicc <- function(x,digits=max(4,getOption("digits")-4),...)
{
  cat("\n")
  cat("Indistinguishable Members: Intraclass Correlation")
  cat("\n\n Call: \n")
  cat("",deparse(x$call), "\n\n")
  cat(" Data",  if (length(x$data[,1]) <= 5) ": " else " (5 first rows shown): ", "\n")
  print( if (length(x$data[,1]) >= 5) x$data[1:5,] else x$data[1:length(x$data),])
  cat("\n\n")
  cat("Descriptive Statistics","\n")
  print.table(x$stats, digits=digits)
  cat("\n\n")
  cat("F Test: ","\n")
  results <- cbind(rbind(x$MSb,x$MSw),rbind(x$df1,x$df2),rbind(x$Fstat,NA),rbind(x$pval,NA))
  colnames(results) <- c("Mean Sq", "Df", "F value", "Pr(>|F|)")
  rownames(results) <- c("Between-Dyads","Within-Dyads")
  print.table(results,digits=digits)
  cat("\n\n")
  cat(paste("Intraclass Correlation and ",(1-x$alpha)*100,"% Confidence Interval: ",sep=''),"\n")
  results <- cbind(x$intracor,t(x$iccCI))
  colnames(results) <- c("ICC", "Lower","Upper")
  rownames(results) <- ''
  print.table(results,digits=digits)
  cat("\n\n")
  invisible(x)
}